name: "Validation"

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
env:
  node-version: 18.x

jobs:
  eslint:
    runs-on: ubuntu-latest
    name: 'ESLint'
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4
      - name: Use Node.js ${{ env.node-version }}
        uses: actions/setup-node@v4
        with:
          node-version: ${{ env.node-version }}
          cache: "npm"
      - name: Install Dependencies
        run: npm clean-install
      - name: Validate JS Sources
        run: npm run validate:js
  markdownlint:
    runs-on: ubuntu-latest
    name: 'MarkdownLint'
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4
      - name: Validate Markdown Sources
        uses: nosborn/github-action-markdown-cli@v3.3.0
        with:
          files: .
